#!/bin/bash

# If the environment variable ROS_VERSION_SELECT_DIR has not been defined, just exit.
if [[ -z "$ROS_VERSION_SELECT_DIR" ]]; then
  echo "Sorry, the environment variable 'ROS_VERSION_SELECT_DIR' has not been defined. Please, set it in order to use ros-version-select utilities."
  return
fi


# Function to be called after completing a "setup command".
rvs_cleanup_command() {
  # TODO: I would love to execute something like this:
  #   gnome-terminal && exit
  # however, it does not start a "fresh terminal"...
  echo "Switch completed! Please close this terminal and open a new one :)"
}


# Function that can be used to source a specific ROS version.
# It accepts one parameter, consisting in the ROS version to be sourced. It can
# be anything, but any value different from 1 or 2 will "deactivate" ROS.
rvs_source_rosX() {
  if [[ $1 != 1 && $1 != 2 ]]; then
    echo "All ROS versions have been deactivated"
  else
    source "$ROS_VERSION_SELECT_DIR/config-ros$ROS_VERSION_SELECT_USE_VERSION.bash"
  fi
}


# Function that annotates the ROS version to be used when opening a new console.
# It takes one parameter: the target ROS version.
rvs_activate_rosX() {
  version_file="$ROS_VERSION_SELECT_DIR/ros-version.bash"
  touch "$version_file"
  echo "# THIS FILE WAS AUTOGENERATED. PLEASE DO NOT MODIFY ITS CONTENT DIRECTLY." > "$version_file"
  if [[ $1 != 1 && $1 != 2 ]]; then
    echo "export ROS_VERSION_SELECT_USE_VERSION=0" >> "$version_file"
  else
    echo "export ROS_VERSION_SELECT_USE_VERSION=$1" >> "$version_file"
  fi
}


# Forward calls to rvs_activate_rosX and then to rvs_cleanup_command.
rvs_activate_rosX_and_cleanup() {
  rvs_activate_rosX $1
  rvs_cleanup_command $1
}


# These are basically aliases to (de)activate ROS.
deactivate_ros() { rvs_activate_rosX_and_cleanup 0; }
activate_ros1() { rvs_activate_rosX_and_cleanup 1; }
activate_ros2() { rvs_activate_rosX_and_cleanup 2; }


# If the version file 'ros-version.bash' does not exist, generate an empty one.
if [ ! -f "$ROS_VERSION_SELECT_DIR/ros-version.bash" ]; then rvs_activate_rosX 0; fi
# Finally, source the proper ros version
source "$ROS_VERSION_SELECT_DIR/ros-version.bash"
rvs_source_rosX "$ROS_VERSION_SELECT_USE_VERSION"
